name: mobile_waiter
description: App Mozo — Bistró Digital
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  socket_io_client: ^3.0.2
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
